name: CI - API Gateway

on:
  push:
    branches: ['master']
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api-gateway-ci.yml'
      - '.github/workflows/docker-build-push.yml'
  pull_request:
    branches: ['master']
    paths:
      - 'api-gateway/**'
      - '.github/workflows/api-gateway-ci.yml'
      - '.github/workflows/docker-build-push.yml'

jobs:
  call-reusable-build:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      service_name: api-gateway
      service_context: ./api-gateway
      docker_tag: ${{ vars.user }}/${{ vars.app }}:api-gateway
    secrets: inherit