name: Build and Push Docker Images

on:
  push:
    branches: 
      - 'master' 
  pull_request:
    branches:
      - 'master'

jobs:
  build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [tickets-manage-ms, api-tickets, frontend, api-gateway, auth-ms]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push ${{ matrix.service }} image
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: |
            ${{ vars.user }}/${{ vars.app }}:${{ matrix.service }}:${{ github.sha }}
            ${{ vars.user }}/${{ vars.app }}:${{ matrix.service }}:latest