name: Reusable Docker Build and Push

on:
  workflow_call: 
    inputs: 
      service_name:
        required: true
        type: string
      service_context:
        required: true
        type: string
      docker_tag:
        required: true
        type: string
    secrets: 
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push ${{ inputs.service_name }} image
        id: build-push
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.service_context }}
          file: ${{ inputs.service_context }}/Dockerfile
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }} # Push solo en merges/pushes a master
          tags: |
            ${{ inputs.docker_tag }}
            ${{ inputs.docker_tag }}-${{ steps.sha.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max