name: CI - Frontend

on:
  push:
    branches: ['master']
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/workflows/docker-build-push.yml' 
  pull_request:
    branches: ['master']
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml'
      - '.github/workflows/docker-build-push.yml'

jobs:
  call-reusable-build:
    uses: ./.github/workflows/docker-build-push.yml 
    with:
      service_name: frontend
      service_context: ./frontend
      docker_tag: ${{ vars.user }}/${{ vars.app }}:frontend
    secrets: inherit 